contactform:
  description: This is a demo contact form and does not work. You can configure it
    to work on your side.
  emailconfig: abc
facts:
  experience: 5
  projects: 25
  customers: 100
keywords: portfolio, website, netlify, jekyll, data-engineer, application-analyst
author:
  resumelink: https://google.com
  name: Prince
  cvlink: https://google.com
  phone: +1 123 456 7890
  first: Princewill
  address: Lagos, Nigeria
  last: Eze
  dob: 10 Sep 2051
  passion: Data Engineering, DevOps, Web Development
  languages: "Igbo, English, French, "
  image: /assets/uploads/bh.jpg
  nationality: Nigerian
  email: princewill.ezeidei@gmail.com
  description: A Data Engineer, Platform Owner, and Big Data Stack Administrator
    charged with the  delivery of strategic data initiatives and the enablement
    of data driven practices to  support Business operations and objectives. I
    have a fine blend of business and  technical skills. Contributed
    significantly towards the creation and documentation of  the Digital and
    Data Strategy for my employer and took on the role of the data engineer  in
    the execution of these strategies.
social:
  facebook: ikaushalpatel
  github: mrkaushal
  instagram: mr.kaushal.p
  linkedin: mrkaushalp
  twitter: mr_kaushal_p
  website: spece.netlify.app
collections:
  portfolio:
    output: true
title: Beauhomme's Portfolio Theme
description: Mr. Homme
baseurl: ""
