contactform:
  description: This is a demo contact form and does not work. You can configure it
    to work on your side.
  emailconfig: abc
facts:
  experience: 5
  projects: 25
  customers: 100
keywords: portfolio, website, netlify, jekyll, data-engineer, application-analyst
author:
  resumelink: https://google.com
  name: Princewill Eze
  cvlink: https://google.com
  phone: +1 123 456 7890
  first: Princewill
  address: Lagos, Nigeria
  last: Eze
  dob: 01 Jan 2000
  passion: Web Developer, Graphic Designer
  languages: English, Gujarati, Hindi
  image: /assets/uploads/1633258134208_1.png
  nationality: Nigerian
  email: princewill.ezeidei@gmail.com
  description: I am a Web Developer from India. I am very passionate and dedicated
    to my work. I have 5 years more work experience. I enjoy working in a team
    or individual.
social:
  facebook: ikaushalpatel
  github: mrkaushal
  instagram: mr.kaushal.p
  linkedin: mrkaushalp
  twitter: mr_kaushal_p
  website: spece.netlify.app
collections:
  portfolio:
    output: true
title: Beauhomme's Portfolio Theme
description: Mr. Homme
baseurl: ""
